brasileirao = [
    "Atlético Mineiro",
    "Bahia",
    "Botafogo",
    "Ceará",
    "Corinthians",
    "Cruzeiro",
    "Flamengo",
    "Fluminense",
    "Fortaleza",
    "Grêmio",
    "Internacional",
    "Juventude",
    "Mirassol",
    "Palmeiras",
    "Red Bull Bragantino",
    "Santos",
    "São Paulo",
    "Sport",
    "Vasco da Gama",
    "Vitória"
]

laliga = [
    "Athletic Bilbao",
    "Atlético Madrid",
    "Barcelona",
    "Real Madrid",
    "Real Betis",
    "Getafe",
    "Osasuna",
    "Rayo Vallecano",
    "Sevilla",
    "Celta Vigo",
    "Alavés",
    "Espanyol",
    "Girona",
    "Villarreal",
    "Valencia",
    "Real Sociedad",
    "Mallorca",
    "Levante",
    "Elche",
    "Oviedo"
]

premier_league = [
    "Arsenal",
    "Aston Villa",
    "Bournemouth",
    "Brentford",
    "Brighton & Hove Albion",
    "Burnley",
    "Chelsea",
    "Crystal Palace",
    "Everton",
    "Fulham",
    "Leeds United",
    "Liverpool",
    "Manchester City",
    "Manchester United",
    "Newcastle United",
    "Nottingham Forest",
    "Sunderland",
    "Tottenham Hotspur",
    "West Ham United",
    "Wolverhampton Wanderers"
]

serie_a = [
    "AC Milan",
    "Atalanta",
    "Bologna",
    "Cagliari",
    "Como",
    "Empoli",
    "Fiorentina",
    "Genoa",
    "Inter Milan",
    "Juventus",
    "Lazio",
    "Lecce",
    "Monza",
    "Napoli",
    "Parma",
    "Roma",
    "Torino",
    "Udinese",
    "Venezia",
    "Verona"
]

bundesliga = [
    "Augsburg",
    "Bayer Leverkusen",
    "Bayern Munich",
    "Borussia Dortmund",
    "Borussia Mönchengladbach",
    "Eintracht Frankfurt",
    "FC St. Pauli",
    "Freiburg",
    "Hamburger SV",
    "Heidenheim",
    "Hoffenheim",
    "Köln",
    "Mainz",
    "RB Leipzig",
    "Stuttgart",
    "Union Berlin",
    "Werder Bremen",
    "Wolfsburg"
]

ligue_1 = [
    "Angers",
    "Auxerre",
    "Brest",
    "Le Havre",
    "Lens",
    "Lille",
    "Lorient",
    "Lyon",
    "Marseille",
    "Metz",
    "Monaco",
    "Nantes",
    "Nice",
    "Paris FC",
    "Paris Saint-Germain",
    "Rennes",
    "Strasbourg",
    "Toulouse"
]

liga_pro = [
    "Aldosivi",
    "Argentinos Juniors",
    "Atlético Tucumáan",
    "Banfield",
    "Barracas Central",
    "Belgrano",
    "Boca Juniors",
    "Central Córdodoba (Santiago del Estero)",
    "Defensa y Justicia",
    "Deportivo Riestra",
    "Estudiantes",
    "Gimnasia La Plata",
    "Godoy Cruz",
    "Huracá",
    "Independiente",
    "Independiente Rivadavia",
    "Platense",
    "Racing Club",
    "River Plate",
    "Vélelez Sarsfield"
]
